# These are supported funding model platforms
github: [efonsecab]
custom: [
'https://www.buymeacoffee.com/efonsecab',
'https://www.amazon.com/kindle-dbs/entity/author/B07QZKVV2C?_encoding=UTF8&node=283155&offset=0&pageSize=12&searchAlias=stripbooks&sort=author-sidecar-rank&page=1&langFilter=default#formatSelectorHeader',
'https://www.patreon.com/pticostarica',
'https://amzn.to/3zmTFEy']
