// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlaySocial.DataAccess.Models
{
    [Index("ApplicationUserId", "ApplicationRoleId", Name = "UI_ApplicationUserRole", IsUnique = true)]
    public partial class ApplicationUserRole
    {
        [Key]
        public long ApplicationUserRoleId { get; set; }
        public long ApplicationUserId { get; set; }
        public short ApplicationRoleId { get; set; }
        public DateTimeOffset RowCreationDateTime { get; set; }
        [Required]
        [StringLength(256)]
        public string RowCreationUser { get; set; }
        [Required]
        [StringLength(250)]
        public string SourceApplication { get; set; }
        [Required]
        [Column("OriginatorIPAddress")]
        [StringLength(100)]
        public string OriginatorIpaddress { get; set; }

        [ForeignKey("ApplicationRoleId")]
        [InverseProperty("ApplicationUserRole")]
        public virtual ApplicationRole ApplicationRole { get; set; }
        [ForeignKey("ApplicationUserId")]
        [InverseProperty("ApplicationUserRole")]
        public virtual ApplicationUser ApplicationUser { get; set; }
    }
}