// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlaySocial.DataAccess.Models;

[Index("GroupMemberId", "MemberApplicationUserId", Name = "UI_GroupMember_GroupMemberId_MemberApplicationUserId", IsUnique = true)]
public partial class GroupMember
{
    [Key]
    public long GroupMemberId { get; set; }

    public long MemberApplicationUserId { get; set; }

    public DateTimeOffset RowCreationDateTime { get; set; }

    [Required]
    [StringLength(256)]
    public string RowCreationUser { get; set; }

    [Required]
    [StringLength(250)]
    public string SourceApplication { get; set; }

    [Required]
    [Column("OriginatorIPAddress")]
    [StringLength(100)]
    public string OriginatorIpaddress { get; set; }

    [ForeignKey("MemberApplicationUserId")]
    [InverseProperty("GroupMember")]
    public virtual ApplicationUser MemberApplicationUser { get; set; }
}