// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlaySocial.DataAccess.Models;

public partial class Post
{
    [Key]
    public long PostId { get; set; }

    [Required]
    [StringLength(500)]
    public string Text { get; set; }

    public long PhotoId { get; set; }

    public long OwnerApplicationUserId { get; set; }

    public DateTimeOffset RowCreationDateTime { get; set; }

    [Required]
    [StringLength(256)]
    public string RowCreationUser { get; set; }

    [Required]
    [StringLength(250)]
    public string SourceApplication { get; set; }

    [Required]
    [Column("OriginatorIPAddress")]
    [StringLength(100)]
    public string OriginatorIpaddress { get; set; }

    [InverseProperty("Post")]
    public virtual ICollection<LikedPost> LikedPost { get; } = new List<LikedPost>();

    [ForeignKey("OwnerApplicationUserId")]
    [InverseProperty("Post")]
    public virtual ApplicationUser OwnerApplicationUser { get; set; }

    [ForeignKey("PhotoId")]
    [InverseProperty("Post")]
    public virtual Photo Photo { get; set; }
}