// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlaySocial.DataAccess.Models;

[Index("PostId", "Url", Name = "UI_PostUrl_PostId_Url", IsUnique = true)]
public partial class PostUrl
{
    [Key]
    public long PostUrlId { get; set; }

    public long PostId { get; set; }

    [Required]
    [StringLength(1000)]
    public string Url { get; set; }

    [ForeignKey("PostId")]
    [InverseProperty("PostUrl")]
    public virtual Post Post { get; set; }
}