// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlaySocial.DataAccess.Models;

[Index("Name", Name = "UI_PostType_Name", IsUnique = true)]
public partial class PostType
{
    [Key]
    public byte PostTypeId { get; set; }

    [Required]
    [StringLength(10)]
    public string Name { get; set; }

    [InverseProperty("PostType")]
    public virtual ICollection<Post> Post { get; } = new List<Post>();
}