// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlaySocial.DataAccess.Models;

public partial class Post
{
    [Key]
    public long PostId { get; set; }

    public short PostVisibilityId { get; set; }

    public long? PhotoId { get; set; }

    [Required]
    [StringLength(500)]
    public string Text { get; set; }

    public long OwnerApplicationUserId { get; set; }

    public DateTimeOffset RowCreationDateTime { get; set; }

    [Required]
    [StringLength(256)]
    public string RowCreationUser { get; set; }

    [Required]
    [StringLength(250)]
    public string SourceApplication { get; set; }

    [Required]
    [Column("OriginatorIPAddress")]
    [StringLength(100)]
    public string OriginatorIpaddress { get; set; }

    public long? CreatedFromPostId { get; set; }

    [ForeignKey("CreatedFromPostId")]
    [InverseProperty("InverseCreatedFromPost")]
    public virtual Post CreatedFromPost { get; set; }

    [InverseProperty("Post")]
    public virtual ICollection<DislikedPost> DislikedPost { get; } = new List<DislikedPost>();

    [InverseProperty("CreatedFromPost")]
    public virtual ICollection<Post> InverseCreatedFromPost { get; } = new List<Post>();

    [InverseProperty("Post")]
    public virtual ICollection<LikedPost> LikedPost { get; } = new List<LikedPost>();

    [ForeignKey("OwnerApplicationUserId")]
    [InverseProperty("Post")]
    public virtual ApplicationUser OwnerApplicationUser { get; set; }

    [ForeignKey("PhotoId")]
    [InverseProperty("Post")]
    public virtual Photo Photo { get; set; }

    [InverseProperty("Post")]
    public virtual ICollection<PostTag> PostTag { get; } = new List<PostTag>();

    [InverseProperty("Post")]
    public virtual ICollection<PostUrl> PostUrl { get; } = new List<PostUrl>();

    [ForeignKey("PostVisibilityId")]
    [InverseProperty("Post")]
    public virtual PostVisibility PostVisibility { get; set; }
}