// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlaySocial.DataAccess.Models;

public partial class PostReach
{
    [Key]
    public long PostReachId { get; set; }

    public long ReachedByApplicationUserId { get; set; }

    public long PostId { get; set; }

    public DateTimeOffset RowCreationDateTime { get; set; }

    [Required]
    [StringLength(256)]
    public string RowCreationUser { get; set; }

    [Required]
    [StringLength(250)]
    public string SourceApplication { get; set; }

    [Required]
    [Column("OriginatorIPAddress")]
    [StringLength(100)]
    public string OriginatorIpaddress { get; set; }

    [ForeignKey("PostId")]
    [InverseProperty("PostReach")]
    public virtual Post Post { get; set; }

    [ForeignKey("ReachedByApplicationUserId")]
    [InverseProperty("PostReach")]
    public virtual ApplicationUser ReachedByApplicationUser { get; set; }
}