// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlaySocial.DataAccess.Models;

public partial class ProfileVisitor
{
    [Key]
    public long ProfileVisitorId { get; set; }

    public long VisitorApplicationUserId { get; set; }

    public long VisitedApplicationUserId { get; set; }

    public DateTimeOffset RowCreationDateTime { get; set; }

    [Required]
    [StringLength(256)]
    public string RowCreationUser { get; set; }

    [Required]
    [StringLength(250)]
    public string SourceApplication { get; set; }

    [Required]
    [Column("OriginatorIPAddress")]
    [StringLength(100)]
    public string OriginatorIpaddress { get; set; }

    [ForeignKey("VisitedApplicationUserId")]
    [InverseProperty("ProfileVisitorVisitedApplicationUser")]
    public virtual ApplicationUser VisitedApplicationUser { get; set; }

    [ForeignKey("VisitorApplicationUserId")]
    [InverseProperty("ProfileVisitorVisitorApplicationUser")]
    public virtual ApplicationUser VisitorApplicationUser { get; set; }
}