// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlaySocial.DataAccess.Models;

[Index("ApplicationUserId", Name = "UI_UserProfile_ApplicationUserId", IsUnique = true)]
public partial class UserProfile
{
    [Key]
    public long UserProfileId { get; set; }

    public long ApplicationUserId { get; set; }

    [Required]
    [StringLength(500)]
    public string Bio { get; set; }

    [StringLength(50)]
    public string LinkedInNickname { get; set; }

    [StringLength(50)]
    public string TwitterNickname { get; set; }

    [StringLength(50)]
    public string FacebookNickname { get; set; }

    [StringLength(50)]
    public string InstagramNickname { get; set; }

    [StringLength(50)]
    public string YouTubeNickname { get; set; }

    [ForeignKey("ApplicationUserId")]
    [InverseProperty("UserProfile")]
    public virtual ApplicationUser ApplicationUser { get; set; }
}