// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlaySocial.DataAccess.Models;

public partial class VisitorTracking
{
    [Key]
    public long VisitorTrackingId { get; set; }

    public long? ApplicationUserId { get; set; }

    [Required]
    [StringLength(250)]
    public string RemoteIpAddress { get; set; }

    [Required]
    [StringLength(250)]
    public string Country { get; set; }

    public DateTimeOffset VisitDateTime { get; set; }

    [Required]
    public string UserAgent { get; set; }

    [Required]
    public string Host { get; set; }

    [Required]
    public string VisitedUrl { get; set; }

    public Guid? SessionId { get; set; }

    public DateTimeOffset? LastTrackedDateTime { get; set; }

    [ForeignKey("ApplicationUserId")]
    [InverseProperty("VisitorTracking")]
    public virtual ApplicationUser ApplicationUser { get; set; }
}